server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://34.236.8.86:1433;databaseName=AltavistaDB;encrypt=false;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:MiPassword123!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
