server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://54.87.114.182:1433;databaseName=AltavistaDB;encrypt=false;trustServerCertificate=true
    username: sa
    password: MiPassword123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
