server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:sqlserver://52.90.18.182:1433;databaseName=AltavistaDB;encrypt=false;trustServerCertificate=true
    username: sa
    password: MiPassword123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none   # ← IMPORTANTE: cambia "update" por "none"
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
